#server:
#  port: 8080
#  shutdown: graceful
#
#logging:
#  level[net.talaatharb.invoicetracker]: DEBUG
#  level[org.springframework.web]: DEBUG
#
#spring:
#  main:
#    allow-circular-references: true
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#  datasource:
#      driverClassName: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/othercode
#      username: root
#      password: awad36148
#  jpa:
#      database: mysql
#      open-in-view: false
#      hibernate.ddl-auto: create-drop
#      generate-ddl: true
#      show-sql: false
#  application:
#    name: invoice-tracker-backend
#  lifecycle:
#    timeout-per-shutdown-phase: 30s
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#      probes:
#        enabled: true

spring:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    #    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.format_sql: true
    generate-ddl: true

  datasource:
    driverClassName: ${DB_DRIVER}
    url: ${DB_HOST}
    #    url: jdbc:postgresql://localhost:5432/invoiceDB
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    protocol: smtp
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

    application:
      name: invoice-tracker-backend
    lifecycle:
      timeout-per-shutdown-phase: 30s



server:
  port: 8080
  shutdown: graceful

logging:
  level[net.talaatharb.invoicetracker]: DEBUG
  level[org.springframework.web]: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
